### ISSUE TITLE
Glitch.com error

### ISSUE THREAD

**Issue by Youtube-itzhacker** [gomashio1596/Fortnite-LobbyBot#11]
When I put the project in glitch it asks me to put the exchange code, I put it but then when I put it in uptime robot glitch closes

**Comment by gomashio1596** [comment]
What do  yo mean "glitch closes"?
Can you send screenshot or video?

**Comment by Vaultonics** [comment]
Where do i get the exchange code from?

**Comment by BayGamerYT** [comment]
> Where do i get the exchange code from?

From [this link](https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode)

**Comment by Vaultonics** [comment]
How do you make a welcome message?

**Comment by gomashio1596** [comment]
![image](https://user-images.githubusercontent.com/53356872/88259308-f6a42980-ccfc-11ea-9bcc-0aa23dbab092.png)
use these
