### ISSUE TITLE
Repl.it hosting is not working 24/7

### ISSUE THREAD

**Issue by ka1888868** [gomashio1596/Fortnite-LobbyBot#73]
Hi, I'm using the project on Repl.it and I used Uptime Robot for ping the website every 5 minutes but when I close the tab of the repl I get the project off and then I need to turn it on again that's mean it's not keeping alive itself. So please help and fix this issue.

**Comment by gomashio1596** [comment]
Looks like for some reason Uptimerobot won't work
Try use https://publicpinger.gomashio1596.repl.co
If this don't work too, try recreate project(You can copy config.json etc. from old project to fast setup)
