### ISSUE TITLE
Error when running RUN.bat

### ISSUE THREAD

**Issue by Lesgosf** [gomashio1596/Fortnite-LobbyBot#83]
Traceback (most recent call last):
  File "index.py", line 1932, in load_json
    data = json.load(f)
  File "C:\Users\MSi\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\MSi\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\MSi\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MSi\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 19 (char 41)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 6655, in <module>
    if not load_config():
  File "index.py", line 1943, in load_config
    data = load_json("config.json")
  File "index.py", line 1935, in load_json
    data = json.load(f)
  File "C:\Users\MSi\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'shift_jis' codec can't decode byte 0x83 in position 2664: illegal multibyte sequence

**Comment by gomashio1596** [comment]
Something wrong in config.json line 4
Please check if your json is correct

**Comment by Lesgosf** [comment]
> Something wrong in config.json line 4
> Please check if your json is correct

  
{
    "fortnite": {
        "email": [dsajsdasd@gmail.com],
        "owner": [Lesgo.],
        "platform": "WIN",
        "outfit": "CID_028_athena_commando_f",
        "outfit_style": "",
        "backpack": "BID_374_cuberockerpunk_female",
        "backpack_style": "",
        "pickaxe": "Pickaxe_id_294_candycane",
        "pickaxe_style": "",
        "emote": "EID_twisteternity_sync",
        "playlist": "Playlist_Tutorial_1",
        "banner": "Bannertoken_026_s11_badge_05",
        "banner_color": "defaultcolor22",
        "avatar_id": "cid_005_athena_commando_m_default",
        "avatar_color": "#ffffff,#ffffff,#ffffff",
        "level": 420,
        "tier": 420,
        "xpboost": 69,
        "friendxpboost": 69,
        "status": "eating coochie",
        "privacy": "public",
        "whisper": false,
        "partychat": true,
        "disablewhisperperfectly": false,
        "disablepartychatperfectly": false,
        "ignorebot": true,
        "joinmessage": "Follow me on TikTok! @Lesgo._",
        "randommessage": [
            "1",
            "2",
            "3",
            "4",
            "5"
        ],
        "joinmessageenable": true,
        "randommessageenable": false,
        "joinemote": true,
        "click_invite": true,
        "disable_voice": false,
        "outfitmimic": false,
        "backpackmimic": false,
        "pickaxemimic": false,
        "emotemimic": false,
        "mimic-ignorebot": true,
        "mimic-ignoreblacklist": true,
        "outfitlock": false,
        "backpacklock": false,
        "pickaxelock": false,
        "emotelock": false,
        "acceptinvite": false,
        "acceptfriend": true,
        "addfriend": false,
        "invite-ownerdecline": false,
        "inviteinterval": true,
        "interval": 30,
        "waitinterval": 10,
        "hide-user": false,
        "hide-blacklist": true,
        "show-owner": true,
        "show-whitelist": true,
        "show-bot": true,
        "blacklist": [
            "Tfue",
            "Ninja"
        ],
        "blacklist-declineinvite": true,
        "blacklist-autoblock": false,
        "blacklist-autokick": true,
        "blacklist-autochatban": false,
        "blacklist-ignorecommand": true,
        "whitelist": [
            "Crazy_Shotyan",
            "CR.Daruma"
        ],
        "whitelist-allowinvite": true,
        "whitelist-declineinvite": true,
        "whitelist-ignorelock": true,
        "whitelist-ownercommand": false,
        "whitelist-ignoreng": true,
        "invitelist": [],
        "otherbotlist": []
    },
    "discord": {
        "enabled": false,
        "token": "Discord Botのトークン",
        "owner": [
            123456789
        ],
        "channels": [
            "{name}-command-channel",
            "bot-command-channel"
        ],
        "status": "ステータス",
        "status_type": "playing",
        "discord": true,
        "disablediscordperfectly": false,
        "ignorebot": true,
        "blacklist": [],
        "blacklist-ignorecommand": true,
        "whitelist": [],
        "whitelist-ignorelock": true,
        "whitelist-ownercommand": false,
        "whitelist-ignoreng": true
    },
    "web": {
        "enabled": true,
        "ip": "{ip}",
        "port": 8000,
        "password": "",
        "login_required": true,
        "web": true,
        "log": false
    },
    "replies-matchmethod": "full",
    "ng-words": [],
    "ng-word-matchmethod": "contains",
    "ng-word-kick": true,
    "ng-word-chatban": true,
    "ng-word-blacklist": false,
    "lang": "en",
    "search-lang": "en",
    "sub-search-lang": "en",
    "restart_in": 0,
    "search_max": 60,
    "no-logs": false,
    "ingame-error": true,
    "discord-log": false,
    "omit-over2000": true,
    "skip-if-overflow": true,
    "hide-email": true,
    "hide-token": true,
    "hide-webhook": true,
    "webhook": "",
    "caseinsensitive": true,
    "loglevel": "normal",
    "debug": false,
    "status": 0
}

**Comment by BayGamerYT** [comment]
@Lesgosf This is the problem
![imagen](https://user-images.githubusercontent.com/60859158/95662837-fabf3680-0af6-11eb-850f-9bf285b66664.png)

Those are lists and they also need quotes because what you need to put there is text
Change that just like this:
```json
"email": ["dsajsdasd@gmail.com"],
"owner": ["Lesgo."],
```
