### ISSUE TITLE
New Issue! Fortnitepy Not found

### ISSUE THREAD

**Issue by Lesgosf** [gomashio1596/Fortnite-LobbyBot#84]
I get the error "Traceback (most recent call last):
  File "D:\among us\Fortnite-LobbyBot-master\index.py", line 60, in <module>
    import fortnitepy
ModuleNotFoundError: No module named 'fortnitepy'" Any fix?

**Comment by gomashio1596** [comment]
Make sure you runned INSTALL.bat

**Comment by Lesgosf** [comment]
> Make sure you runned INSTALL.bat

I did, It cannot install lmxl for some reason.

**Comment by gomashio1596** [comment]
lmxl?
Was there a error when you runned INSTALL.bat?
